# Generated by Django 3.2.10 on 2022-02-19 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credits', '0012_auto_20220219_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('pay_day', models.DateField(blank=True, default=None, null=True)),
                ('state', models.IntegerField(choices=[(0, 'Creado'), (1, 'Pagado'), (2, 'Fallido')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.credit')),
            ],
        ),
    ]
