# Generated by Django 3.2.10 on 2022-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payed_day',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Fallido')], default=0),
        ),
    ]
