# Generated by Django 3.2.10 on 2021-12-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('DNI', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('marital_state', models.IntegerField(choices=[(0, 'Soltero(a)'), (1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Comprometido(a)')], default=0)),
                ('spouse', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('children', models.IntegerField(default=0)),
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prospects.prospect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prospects.prospect')),
                ('relationship', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='prospects.client')),
            ],
        ),
        migrations.CreateModel(
            name='Aval',
            fields=[
                ('prospect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prospects.prospect')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avals', to='prospects.client')),
            ],
        ),
    ]
