# Generated by Django 3.2.10 on 2021-12-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='children',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='job',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='spouse',
        ),
        migrations.AddField(
            model_name='client',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='job',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='spouse',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
