# Generated by Django 3.2.10 on 2022-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='marital_state',
            field=models.IntegerField(choices=[(0, 'Soltero(a)'), (1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Comprometido(a)'), (4, 'Padre Soltero(a)'), (5, 'Viudo(a)'), (6, 'Unión Libre)')], default=0),
        ),
    ]
