# Generated by Django 3.2.10 on 2021-12-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_auto_20211211_0234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='marital_status',
        ),
        migrations.AddField(
            model_name='client',
            name='marital_state',
            field=models.IntegerField(choices=[(0, 'Soltero(a)'), (1, 'Casado(a)'), (2, 'Divorciado(a)'), (3, 'Comprometido(a)')], default=0),
        ),
    ]
