# Generated by Django 3.2.10 on 2022-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0003_alter_client_marital_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
