# Generated by Django 3.2.10 on 2021-12-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0004_auto_20211212_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='contacte',
            new_name='contact',
        ),
    ]
