# Generated by Django 3.2.10 on 2021-12-12 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0005_rename_contacte_reference_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='prospects.client'),
            preserve_default=False,
        ),
    ]
