# Generated by Django 3.2.10 on 2021-12-11 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=50)),
                ('request_amount', models.IntegerField(default=0)),
                ('authorized_amount', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(0, 'Creado'), (1, 'Completado'), (2, 'Fallido')], default=0)),
                ('cycle', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prospects.client')),
            ],
        ),
    ]
