# Generated by Django 3.2.10 on 2021-12-08 01:29

import credits.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=50)),
                ('request_amount', models.IntegerField(default=0)),
                ('authorized_amount', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(credits.models.CreditState['CREATED'], 0), (credits.models.CreditState['AUTHORIZED'], 1), (credits.models.CreditState['COMPLETED'], 2)], default=0)),
                ('cycle', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
