# Generated by Django 3.2.10 on 2021-12-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='cycle',
            field=models.IntegerField(choices=[(0, 'Semanal')], default=0),
        ),
        migrations.AlterField(
            model_name='credit',
            name='folder',
            field=models.CharField(default='Finanzas del sur', max_length=100),
        ),
    ]
