# Generated by Django 3.2.10 on 2021-12-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_auto_20211212_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='term',
            field=models.IntegerField(default=0),
        ),
    ]
