# Generated by Django 3.2.10 on 2021-12-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prospects', '0002_alter_prospect_phone_number'),
        ('credits', '0004_credit_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='prospects.client'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='visit_time',
            field=models.IntegerField(choices=[(9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 PM'), (13, '13:00 PM'), (14, '14:00 PM'), (15, '15:00 PM'), (16, '16:00 PM'), (17, '17:00 PM'), (18, '18:00 PM'), (19, '19:00 PM'), (29, '20:00 PM')], default=0),
        ),
    ]
