# Generated by Django 3.2.10 on 2022-01-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('prospects', '0002_alter_prospect_phone_number'),
        ('credits', '0006_credit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='credit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='prospects.client'),
        ),
    ]
