# Generated by Django 3.2.10 on 2022-01-23 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
        ('credits', '0008_remove_credit_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='folders.folder'),
        ),
    ]
