# Generated by Django 3.2.10 on 2022-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0011_credit_next_visit_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='tarjeton',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credit',
            name='visit_found',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
        ),
    ]
