# Generated by Django 3.2.10 on 2022-02-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_auto_20220219_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='next_pay_day',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='next_visit_day',
        ),
    ]
