# Generated by Django 3.2.10 on 2022-02-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_auto_20220219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='term',
            field=models.IntegerField(default=15),
        ),
    ]
