# Generated by Django 3.2.10 on 2021-12-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prospects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('state', models.IntegerField(default=0)),
                ('suburb', models.CharField(blank=True, max_length=255, null=True)),
                ('township', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.IntegerField(null=True)),
                ('long', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prospect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='prospects.prospect')),
            ],
        ),
    ]
