# Generated by Django 3.2.10 on 2021-12-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('zip', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('suburb', models.CharField(max_length=255)),
                ('township', models.CharField(max_length=255)),
                ('lat', models.IntegerField(null=True)),
                ('long', models.IntegerField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
    ]
