# Generated by Django 3.2.10 on 2021-12-12 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_alter_address_prospect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='township',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
