# Generated by Django 3.2.10 on 2022-02-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0006_auto_20220129_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='long',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
